name: GlyphMatrix PCB

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
  workflow_dispatch:

jobs:
  KiBot-Generation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Generate Gerber, BOM, and Position (CPL) for GlyphMatrix
      uses: INTI-CMNB/KiBot@v1.8.4
      with:
        config: .kibot.yaml
        dir: kicad/production/glyphmatrix
        board: kicad/GlyphMatrix.kicad_pcb
        schema: kicad/GlyphMatrix.kicad_sch

    - name: Zip output files
      run: |
        zip -r --junk-paths glyphyatrix-gerber.zip kicad/production/glyphmatrix/gerber/*
        # zip -r --junk-paths glyphyatrix-pcba.zip kicad/production/glyphmatrix/pcba/*

    - name: GH Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: |
          glyphmatrix-*.zip
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
