name: GlyphMatrix PCB

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
  workflow_dispatch:

jobs:
  KiBot-Generation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Generate Gerber, BOM, and Position (CPL) for GlyphMatrix
      uses: INTI-CMNB/KiBot@v1.8.4
      with:
        config: .kibot.yaml
        dir: kicad/glyphmatrix/gerber
        board: kicad/GlyphMatrix.kicad_pcb
        schema: kicad/GlyphMatrix.kicad_sch

    - name: Run offset_midy_layer.py for GlyphMatrix_CPL.csv
      run: |
        find kicad -type f 
#        python tools/offset_midy_layer.py --filter_value SW_MX_HS --offset -1.27 --new_layer bottom --input_file kicad/glyphmatrix/gerber/GlyphMatrix_CPL.csv

    - name: Zip output files
      run: |
        zip -r --junk-paths glyphmatrix-gerber.zip kicad/glyphmatrix/gerber -x '*bom*' '*cpl*'
        zip -r --junk-paths glyphmatrix-bom.zip . -i kicad/glyphmatrix/gerber/*bom*.csv

    - name: GH Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: |
          glyphmatrix-*.zip
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
