name: GlyphMatrix PCB

on:
  push:
    tags:
      - '[0-9]+.[0-9]+*'
  pull_request:
  workflow_dispatch:

jobs:
  KiBot-Generation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Generate Gerber, BOM, and Position (CPL) for GlyphMatrix
      uses: INTI-CMNB/KiBot@v1.8.4
      with:
        config: .kibot.yaml
        dir: kicad/production/glyphmatrix
        board: kicad/GlyphMatrix.kicad_pcb
        schema: kicad/GlyphMatrix.kicad_sch

    - name: Generate Gerber, BOM, and Position (CPL) for GlyphMatrix Top
      uses: INTI-CMNB/KiBot@v1.8.4
      with:
        config: .kibot.yaml
        dir: kicad/production/glyphmatrix-top
        board: kicad/GlyphMatrix_Top.kicad_pcb

    - name: Generate Gerber, BOM, and Position (CPL) for GlyphMatrix Plate
      uses: INTI-CMNB/KiBot@v1.8.4
      with:
        config: .kibot.yaml
        dir: kicad/production/glyphmatrix-plate
        board: kicad/GlyphMatrix_Plate.kicad_pcb

    - name: Zip output files
      run: |
        zip -r --junk-paths glyphmatrix-gerber.zip kicad/production/glyphmatrix/gerber/*
        # zip -r --junk-paths glyphmatrix-pcba.zip kicad/production/glyphmatrix/pcba/*
        zip -r --junk-paths glyphmatrix-top-gerber.zip kicad/production/glyphmatrix-top/gerber/*
        zip -r --junk-paths glyphmatrix-plate-gerber.zip kicad/production/glyphmatrix-plate/gerber/*

    - name: GH Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: |
          glyphmatrix-gerber.zip
          glyphmatrix-top-gerber.zip
          glyphmatrix-plate-gerber.zip
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
